services:
  - type: web
    name: flask-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:8000"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 8000
    buildFilter:
      paths:
        - backend/**

  - type: static
    name: react-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    buildFilter:
      paths:
        - frontend/**
