"""Adding fields to the district table and updating the import function.

Revision ID: 7a3161d8f5d7
Revises: 948f1be3b1c1
Create Date: 2025-05-31 10:40:31.684401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3161d8f5d7'
down_revision = '948f1be3b1c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###
