"""Updating models.py to include tables related to handling dataset information for metro districts. To be used when comparing against tracked violations to collect homeowner information (name, contact, mailing address, etc).

Revision ID: 948f1be3b1c1
Revises: 
Create Date: 2025-05-31 09:31:24.296023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948f1be3b1c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('lot_number', sa.String(length=50), nullable=False),
    sa.Column('move_in_date', sa.DateTime(), nullable=True),
    sa.Column('address_type', sa.String(length=20), nullable=True),
    sa.Column('service_address', sa.String(length=100), nullable=True),
    sa.Column('service_city_st_zip', sa.String(length=100), nullable=True),
    sa.Column('mail_address', sa.String(length=100), nullable=True),
    sa.Column('mail_city_st_zip', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('ebill_username', sa.String(length=100), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('account_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('field_changed', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('mail_notifications', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_preferences')
    op.drop_table('account_history')
    op.drop_table('accounts')
    op.drop_table('districts')
    # ### end Alembic commands ###
